simplito/privmx-endpoint

- endpoint/inbox/include/privmx/endpoint/inbox/InboxHandleManager.hpp
- endpoint/inbox/include_pub/privmx/endpoint/inbox/InboxException.hpp
- endpoint/inbox/src/InboxApiImpl.cpp
- endpoint/inbox/src/InboxHandleManager.cpp
- endpoint/store/include/privmx/endpoint/store/FileHandle.hpp
- endpoint/store/include_pub/privmx/endpoint/store/StoreException.hpp
- endpoint/store/src/FileHandle.cpp
- endpoint/store/src/StoreApiImpl.cpp
- endpoint/tests_e2e/tests/InboxTest.cpp
- endpoint/tests_e2e/tests/StoreTest.cpp
> fix: file handle closing issue

- endpoint/interface/include/privmx/endpoint/interface/endpoint.h
- endpoint/interface/src/EndpointCInterface.cpp
> feat: Add BackendRequester to C interface

- endpoint/store/include_pub/privmx/endpoint/store/StoreException.hpp
- endpoint/store/src/StoreApiImpl.cpp
- endpoint/tests_e2e/tests/StoreTest.cpp
> 83 bug cannot get file after user removal

- rpc/base/src/AuthorizedConnection.cpp
- rpc/base/src/channel/WebSocketNotify.cpp
- utils/include/privmx/utils/CancellationToken.hpp
- utils/src/CancellationToken.cpp
> 81 refactor privmxutilscancellationtoken   typo in method

- endpoint/core/include_pub/privmx/endpoint/core/Buffer.hpp
- endpoint/core/include_pub/privmx/endpoint/core/Utils.hpp
- endpoint/core/src/Utils.cpp
- endpoint/inbox/src/InboxApiImpl.cpp
- endpoint/tests_e2e/CMakeLists.txt
- endpoint/tests_e2e/tests/UtilsTest.cpp
- utils/include/privmx/utils/Utils.hpp
- utils/src/Utils.cpp
> 96 move headers of utility classes to public

- endpoint/crypto/include/privmx/endpoint/crypto/CryptoApiImpl.hpp
- endpoint/crypto/include_pub/privmx/endpoint/crypto/CryptoApi.hpp
- endpoint/crypto/include_pub/privmx/endpoint/crypto/ExtKey.hpp
- endpoint/crypto/include_pub/privmx/endpoint/crypto/Types.hpp
- endpoint/crypto/src/CryptoApi.cpp
- endpoint/crypto/src/CryptoApiImpl.cpp
- endpoint/crypto/src/ExtKey.cpp
- utils/src/Utils.cpp
> 99 extand crypto api

- endpoint/inbox/include_pub/privmx/endpoint/inbox/Types.hpp
- endpoint/inbox/src/InboxApiImpl.cpp
- endpoint/store/include_pub/privmx/endpoint/store/Types.hpp
- endpoint/store/src/StoreApiImpl.cpp
- endpoint/tests_e2e/test_env/create_docker/DockerSetupData.cpp
- endpoint/thread/include_pub/privmx/endpoint/thread/Types.hpp
- endpoint/thread/src/ThreadApiImpl.cpp
> 132 add datastructureversion

- endpoint/core/include/privmx/endpoint/core/CoreTypes.hpp
- endpoint/core/include_pub/privmx/endpoint/core/Types.hpp
- endpoint/core/include_pub/privmx/endpoint/core/UserVerifierInterface.hpp
- endpoint/core/src/KeyProvider.cpp
- endpoint/inbox/src/InboxApiImpl.cpp
- endpoint/store/src/StoreApiImpl.cpp
- endpoint/thread/src/ThreadApiImpl.cpp
> 140 add to verificationrequest new field bridgeidentity

- endpoint/core/include/privmx/endpoint/core/TimestampValidator.hpp
- endpoint/core/src/ConnectionImpl.cpp
- endpoint/core/src/TimestampValidator.cpp
- endpoint/crypto/include/privmx/endpoint/crypto/CryptoApiImpl.hpp
- endpoint/crypto/include/privmx/endpoint/crypto/KeyConverter.hpp
- endpoint/crypto/include/privmx/endpoint/crypto/varinterface/CryptoApiVarInterface.hpp
- endpoint/crypto/include_pub/privmx/endpoint/crypto/CryptoApi.hpp
- endpoint/crypto/src/CryptoApi.cpp
- endpoint/crypto/src/CryptoApiImpl.cpp
- endpoint/crypto/src/KeyConverter.cpp
- endpoint/crypto/src/varinterface/CryptoApiVarInterface.cpp
- privfs/include/privmx/privfs/gateway/RpcGateway.hpp
- privfs/src/gateway/RpcGateway.cpp
- rpc/base/include/privmx/rpc/AuthorizedConnection.hpp
- rpc/base/include/privmx/rpc/RpcException.hpp
- rpc/base/include/privmx/rpc/Types.hpp
- rpc/base/include/privmx/rpc/tls/ConnectionClient.hpp
- rpc/base/src/AuthorizedConnection.cpp
- rpc/base/src/ConnectionManager.cpp
- rpc/base/src/tls/ConnectionClient.cpp
- utils/include/privmx/utils/Utils.hpp
- utils/src/Utils.cpp
> 142 connection challenge

- endpoint/crypto/src/ExtKey.cpp
> fix: ExtKey::getPublicPartAsBase58()

- endpoint/tests_e2e/tests/CryptoTest.cpp
> 151-update-tests-for-cryptoapi

- endpoint/event/src/EventApiImpl.cpp
- endpoint/tests_e2e/tests/EventsTest.cpp
> 186 custom event dont arrive to the other user when connecting in parallel

- endpoint/inbox/include/privmx/endpoint/inbox/InboxApiImpl.hpp
- endpoint/inbox/src/InboxApiImpl.cpp
- endpoint/kvdb/include/privmx/endpoint/kvdb/KvdbApiImpl.hpp
- endpoint/kvdb/src/KvdbApiImpl.cpp
- endpoint/store/include/privmx/endpoint/store/StoreApiImpl.hpp
- endpoint/store/src/StoreApiImpl.cpp
- endpoint/thread/include/privmx/endpoint/thread/ThreadApiImpl.hpp
- endpoint/thread/src/ThreadApiImpl.cpp
> 181 bug there is no info at all about an item thread store inbox message file entry on error whilst reading from server

- endpoint/core/include/privmx/endpoint/core/Validator.hpp
- endpoint/core/src/Validator.cpp
- endpoint/kvdb/src/KvdbValidator.cpp
- endpoint/tests_e2e/tests/InboxTest.cpp
- endpoint/tests_e2e/tests/KvdbTest.cpp
- endpoint/tests_e2e/tests/StoreTest.cpp
- endpoint/tests_e2e/tests/ThreadTest.cpp
> 184 pagingquery missing validator for queryasjson

- endpoint/core/include/privmx/endpoint/core/CoreTypes.hpp
- endpoint/core/include/privmx/endpoint/core/EventChannelManager.hpp
- endpoint/core/include/privmx/endpoint/core/ServerTypes.hpp
- endpoint/core/include/privmx/endpoint/core/SubscriptionHelper.hpp
- endpoint/core/src/ConnectionImpl.cpp
- endpoint/core/src/EventChannelManager.cpp
- endpoint/core/src/SubscriptionHelper.cpp
- endpoint/event/include/privmx/endpoint/event/EventTypes.hpp
- endpoint/event/include_pub/privmx/endpoint/event/Events.hpp
- endpoint/event/src/EventApiImpl.cpp
- endpoint/inbox/include/privmx/endpoint/inbox/InboxApiImpl.hpp
- endpoint/inbox/src/InboxApiImpl.cpp
- endpoint/kvdb/include/privmx/endpoint/kvdb/KvdbApiImpl.hpp
- endpoint/kvdb/src/KvdbApiImpl.cpp
- endpoint/store/include/privmx/endpoint/store/StoreApiImpl.hpp
- endpoint/store/src/StoreApiImpl.cpp
- endpoint/thread/include/privmx/endpoint/thread/ThreadApiImpl.hpp
- endpoint/thread/src/ThreadApiImpl.cpp
> feat: new event channels handling

- endpoint/core/include_pub/privmx/endpoint/core/cinterface/core.h
- endpoint/core/src/EndpointCoreCInterface.cpp
> feat: privmx_endpoint_setUserVerifier add context parameter

- endpoint/core/include/privmx/endpoint/core/Validator.hpp
- endpoint/core/src/Connection.cpp
- endpoint/core/src/Validator.cpp
- endpoint/inbox/src/InboxApi.cpp
- endpoint/kvdb/src/KvdbApi.cpp
- endpoint/store/src/StoreApi.cpp
- endpoint/tests_e2e/tests/InboxTest.cpp
- endpoint/tests_e2e/tests/KvdbTest.cpp
- endpoint/tests_e2e/tests/StoreTest.cpp
- endpoint/tests_e2e/tests/ThreadTest.cpp
- endpoint/thread/src/ThreadApi.cpp
> 213 finish implementig sortby in threadstoreinbox

- endpoint/core/src/SubscriptionHelper.cpp
- endpoint/tests_e2e/tests/InboxModuleEventsTest.cpp
- endpoint/tests_e2e/tests/KvdbModuleEventsTest.cpp
- endpoint/tests_e2e/tests/StoreModuleEventsTest.cpp
- endpoint/tests_e2e/tests/ThreadModuleEventsTest.cpp
> 235 bug not working unsubscribe for all events in 253

- endpoint/tests_e2e/tests/CoreTest.cpp
> test: Add e2e test for listContextUsers

- endpoint/store/src/FileReader.cpp
> fix: Fix argument type in read in FileReader

- endpoint/store/include/privmx/endpoint/store/Mapper.hpp
- endpoint/store/include_pub/privmx/endpoint/store/Types.hpp
- endpoint/store/src/Mapper.cpp
- endpoint/store/src/StoreApiImpl.cpp
- endpoint/tests_e2e/tests/StoreModuleEventsTest.cpp
> 270 bug file change events report incorrect lengths
